### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by southwestwebdesign** [nneonneo/iOS-SOCKS-Server#22]
Hello, trying to connect from an android or a iOS phone but getting constant issues:

tried both the pac and socks url to no avail, but keep getting C or G error codes.

Assuming proxy will be accessed over hotspot (bridge100) at 172.20.10.1
Will connect to IPv4 servers over interface pdp_ip0 at 10.131.163.42
PAC URL: http://172.20.10.1:8088/wpad.dat
SOCKS Address: 172.20.10.1:9876

Direction    | Traffic (Mbps) 
------------ | ---------------
In           | 0.00           
Out          | 0.00           

Connections:      4
Total In:      0.03 MB
Total Out:     0.01 MB
Total:         0.04 MB

Errors: 841
Last 5 log messages:
    172.20.10.6:42352: Exception: Invalid version 'C' (not configured as SOCKS proxy?)
    172.20.10.6:42354: Exception: Invalid version 'C' (not configured as SOCKS proxy?)
    172.20.10.6:42360: Exception: Invalid version 'C' (not configured as SOCKS proxy?)
    172.20.10.6:42362: Exception: Invalid version 'C' (not configured as SOCKS proxy?)
    172.20.10.6:42366: Exception: Invalid version 'C' (not configured as SOCKS proxy?)
Shutting down.

![Uploading IMG_4331.jpeg…]()

**Comment by nneonneo** [comment]
Your device is attempting to connect to the proxy as an HTTP proxy ("CONNECT"/"GET") rather than as a SOCKS5 proxy. You may need to use the PAC URL to get your device to use the SOCKS5 protocol.

(As a future TODO, it might be cool to have the proxy support *both* SOCKS5 and HTTP via protocol sniffing...)

**Comment by southwestwebdesign** [comment]
Thanks for the reply.

I’ve tried both the pac and socks fields.

I tested on my MacBook Air and it worked without issue, so it’s isolated to a certain android account

**Comment by nneonneo** [comment]
Interesting. I just tested with an Android phone I had kicking around (running Android 13) and it did indeed fail - the SOCKS proxy is being treated as an HTTP proxy even when configured via PAC.

This seems to be a longstanding Android limitation. Unfortunately, I didn't catch this because I use Android very infrequently.

It should not be hard to lift the limitation: we can perform some protocol sniffing to detect if the first byte is an uppercase letter (or just one of "GHPDCOT"?) and if so, treat the connection as an HTTP proxy connection. This should even make the proxy more useful since then there will not be a need to fiddle with PAC URLs in most configurations.

**Comment by southwestwebdesign** [comment]
That sounds like a great idea! 

Thanks for doing further testing on your end to clarify I’m not going insane!

**Comment by nneonneo** [comment]
144e079 adds an HTTP proxy server; I eventually decided against protocol sniffing because it's a bit fragile and usually unnecessary. Port 9877 exports an HTTP proxy server, which should be usable by Android (or really any other client). Give that a whirl.

**Comment by southwestwebdesign** [comment]
Awesome! Ive tried using the latest commit, and the errors are now no longer present and accessing internet led alls through the android device now work, however no MB is being shared and 0 connections is present in the Pythonista. I.e it thinks it can connect however no data is being parsed between?

**Comment by nneonneo** [comment]
Hmm, I thought maybe the statistics tracking might be broken, but I just tested with my Android device and the stats are tracked properly.

If it's working, you can try and check that the IP address is correct, i.e. that visiting one of those "what is my IP address" sites (e.g. https://whatismyipaddress.com/) shows your Pythonista device's cellular ISP instead of your WiFi connection's ISP.

**Comment by nneonneo** [comment]
Resolved through the addition of an HTTP proxy; if you're still having connection issues feel free to open a new issue.
