### ISSUE TITLE
Use with vpn

### ISSUE THREAD

**Issue by jjkakakk** [nneonneo/iOS-SOCKS-Server#26]
Could this potentially work with a VPN being up on the phone, and thus the outbound traffic would go out over the VPN utun device (rather than the first cell0 interface)? Does the outbound proxied (socksified) traffic follow the natural routing table in place on the phone (if the VPN interface is the default gw)? 

Thanks 🙂

**Comment by jjkakakk** [comment]
PS I'm thinking usb-tether, then outbound over socks via vpn ontop of pdp-ip0 (if that helps)

**Comment by nneonneo** [comment]
In principle, this should work. I think you'd need to change the interface selection logic a bit - run the `lib/ifaddrs.py` script to dump out the interfaces, pick the interface name, then change line 102 (https://github.com/nneonneo/iOS-SOCKS-Server/blob/master/socks5.py#L102) to append the iface only if it matches the interface name you want (i.e. `elif iface.name == "utun0"` instead of `else`).

**Comment by jjkakakk** [comment]
Thanks for the response I'll try this out and let you know. 

I'll put a stub of code in that defaults to utun if it has a matching inet w.x.y.z addr, but otherwise continues to default to cell if-addr if not. 

Cheers :)

**Comment by nneonneo** [comment]
Thanks! The interface detection code has long been one of the weak spots in the project since I don't have enough devices or plans to test all possible combinations - so any ideas for improving that code will always be welcome ;)
